# Site
name: "People of Natural Language Processing"
title: "People of Natural Language Processing"
description: "Celebrating the humans behind natural language processing research works"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: People of NLP
    display_name: People of NLP
    avatar: 'assets/images/logo.png'
    email: peopleofnlproc@gmail.com
    web: https://peopleofnlproc.github.io/
    twitter: https://twitter.com/PeopleOfNLProc
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
